# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtWidgets


# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(402, 343)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.pushButton_click = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton_click.setGeometry(QtCore.QRect(120, 270, 151, 31))
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.pushButton_click.setFont(font)
#         self.pushButton_click.setStyleSheet("color: rgb(255, 255, 255);\n"
# "background-color: rgb(85, 170, 255);")
#         self.pushButton_click.setAutoDefault(True)
#         self.pushButton_click.setFlat(False)
#         self.pushButton_click.setObjectName("pushButton_click")
#         self.click_count_label = QtWidgets.QLabel(self.centralwidget)
#         self.click_count_label.setGeometry(QtCore.QRect(130, 100, 181, 71))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         font.setBold(True)
#         font.setWeight(75)
#         self.click_count_label.setFont(font)
#         self.click_count_label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
#         self.click_count_label.setTextFormat(QtCore.Qt.RichText)
#         self.click_count_label.setObjectName("click_count_label")
#         MainWindow.setCentralWidget(self.centralwidget)

#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)

#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.pushButton_click.setText(_translate("MainWindow", "Click Me"))
#         self.click_count_label.setText(_translate("MainWindow", "No. of Clicks: 0"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 350)
        MainWindow.setStyleSheet("background-color: #f0f0f0;")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Click Button
        self.pushButton_click = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_click.setGeometry(QtCore.QRect(120, 270, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.pushButton_click.setFont(font)
        self.pushButton_click.setStyleSheet("""
            QPushButton {
                color: white;
                background-color: #007bff;
                border-radius: 20px;
                border: 2px solid #0056b3;
            }
            QPushButton:hover {
                background-color: #0056b3;
            }
        """)
        self.pushButton_click.setText("Click Me")
        self.pushButton_click.setObjectName("pushButton_click")
        
        # Click Counter Display
        self.click_count_label = QtWidgets.QLabel(self.centralwidget)
        self.click_count_label.setGeometry(QtCore.QRect(130, 100, 140, 140))
        font.setPointSize(14)
        font.setBold(True)
        self.click_count_label.setFont(font)
        self.click_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.click_count_label.setStyleSheet("""
            QLabel {
                color: #333;
                background-color: #ffcc00;
                border-radius: 70px;
                border: 3px solid #ff9900;
            }
        """)
        self.click_count_label.setObjectName("click_count_label")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # Counter Variable
        self.click_count = 0
        self.pushButton_click.clicked.connect(self.update_counter)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interactive Click Counter"))
        self.click_count_label.setText(_translate("MainWindow", "0"))

    def update_counter(self):
        self.click_count += 1
        self.click_count_label.setText(str(self.click_count))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
